### ISSUE TITLE
UCA - Button to make activitytest for individual activities

### ISSUE THREAD

**Issue by Kifo1** [UnicacityAddon/unicacityaddon-addon#775]
### Description

Why is this feature necessary and what should do this feature?

This feature is intended to add a button to messages of arrests and WP-kills you have made yourself, with which you can automatically run the "/activitytest" command. That would simplify the entry of activities a bit.

### Checklist
- [x] Add buttons to WP-kill/arrest messages.

#### Reporter (You)

- [x] Issue name according to naming conventions added (`UCA - <short description>`)
- [x] Feature description added

#### Refinement (We)

- [x] Project linked
- [x] Milestone linked
- [x] Contributor assigned

#### Start issue (We)

- [x] Branch according to naming convention created (`feature/UCA-<issue-number>-<short-description>`)
- [x] Pull request according to naming convention created (`feature/UCA-<issue-number>-<short-description>`)
- [x] Reviewer assigned to pull request

**Comment by rettichlp** [comment]
- Adjust template
- Renamed Issue
