### ISSUE TITLE
UCA - Equipment name not found

### ISSUE THREAD

**Issue by Kifo1** [UnicacityAddon/unicacityaddon-addon#783]
### Description

In the SWAT-Equip, some parts are not recognized correctly because the name in the chat message does not match the one specified in the "Equip" enum.
Screenshop:  https://imgur.com/a/8dssvZT

LabyMod version: 4

Minecraft version: 1.12.2

Addon version: 2.1.0

### Checklist

- [x] Recognize the equipment names

#### Reporter (You)

- [x] Issue name according to naming conventions added (`UCA - <short description>`)
- [x] Bug description added and information provided

#### Refinement (We)

- [x] Project linked
- [x] Milestone linked
- [x] Contributor assigned

#### Start issue (We)

- [x] Branch according to naming convention created (`bug/UCA-<issue-number>-<short-description>`)
- [x] Pull request according to naming convention created (`bug/UCA-<issue-number>-<short-description>`)
- [x] Reviewer assigned to pull request

**Comment by rettichlp** [comment]
![image](https://github.com/UnicacityAddon/unicacityaddon-addon/assets/97811064/faebe58e-a760-4425-90fb-9c63ae2ee7bc)
![image](https://github.com/UnicacityAddon/unicacityaddon-addon/assets/97811064/5481600c-006b-410e-97d5-0e859a91143c)
